import { download } from './download';
import { Link } from 'react-router-dom';
import './styles.css';
import { useState, useEffect, useCallback } from 'react';
import { Globe2, LayoutDashboard, UsersRound, MessageSquareText, ClipboardCheck, ShieldCheck, Bell, Download, Search, ChevronRight, Menu, X, Building2, ArrowUpRight, Info, CircleHelp, FileClock, Sparkles, Activity, ChevronDown } from 'lucide-react';
import { data, allDecisions, nameOf } from './data';
import { rate, summarize, categoryInfo, inScope, wilson, csv } from './metrics.mjs';
import WorldMap from './components/WorldMap';
import { DecisionTable, InterviewsPage, OperatorPage, IssuesPage, LogPage, MethodPage } from './pages';
import DetailDialog from './components/DetailDialog';
import { useLocalAudit } from './useLocalAudit';
import { useWebMcp } from './useWebMcp';
import { Badge, Panel, Empty } from './components/ui';

const navItems = [ ['overview', 'Overview', LayoutDashboard], ['decisions', 'Decisions', ClipboardCheck], ['interviews', 'Interviews', MessageSquareText], ['issues', 'Alerts', Bell], ['log', 'Activity log', FileClock] ];
function parseRoute() { const [type = 'overview', id] = window.location.hash.replace(/^#\/?/, '').split('/'); return { type: type || 'overview', id }; }

function Stats({ rows, interviews, issues }) {
  const stats = summarize(rows);
  return <div className="stats-grid">
    {[['Decisions reviewed', rows.length, `${stats.verified} with independent reference`, ClipboardCheck, 'blue'], ['Interviews recorded', interviews.length, `${interviews.filter(i => i.sentiment_analysis.status === 'available').length} with sentiment available`, MessageSquareText, 'teal'], ['Changed decisions', stats.changed, `${rate(stats.changed, rows.length)} after viewing Cashy`, Activity, 'violet'], ['Open alerts', issues.filter(i => i.status !== 'closed').length, 'For supervisor review', Bell, 'amber']].map(([label, value, caption, Icon, tone]) => <div className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={`stat-icon ${tone}`}><Icon size={18}/></span></div><strong>{value.toString().padStart(2, '0')}</strong><p>{caption}</p></div>)}
  </div>;
}

export function Reliance({ rows }) {
  const stats = summarize(rows);
  return <Panel title="How AI is used" subtitle="Decisions compared with the independent reference" action={<Badge>{stats.verified} verified</Badge>}>
    <div className="reliance-grid">{Object.entries(categoryInfo).filter(([key]) => key !== 'unverified').map(([key, info]) => {
      const total = ['correct_override', 'over_reliance'].includes(key) ? stats.discordant : stats.concordant;
      const n = stats.counts[key]; const interval = wilson(n, total);
      return <div className="reliance-item" key={key}><div><span className={`dot ${info.color}`}/><span>{info.label}</span><strong>{rate(n, total)}</strong></div><div className="bar-track"><div className={info.color} style={{ width: total ? `${n / total * 100}%` : '0%' }}/></div><p>{n} of {total} · AI {['correct_override', 'over_reliance'].includes(key) ? 'incorrect' : 'correct'}{interval ? ` · 95% CI ${Math.round(interval[0] * 100)}–${Math.round(interval[1] * 100)}%` : ''}</p></div>;
    })}</div><div className="panel-footnote"><Info size={14}/><span>Synthetic scenarios · {stats.operators} {stats.operators === 1 ? "operator" : "operators"} · {stats.counts.unverified} {stats.counts.unverified === 1 ? 'unverified case' : 'unverified cases'}. Descriptive Wilson intervals, not adjusted for repeated assessments by the same operator.</span></div>
  </Panel>;
}

function Overview({ rows, interviews, issues, route, navigate, onOpen }) {
  let entities = data.organization.countries.map(c => ({ id: c.id, type: 'country', name: c.display_name, count: data.organization.offices.filter(o => o.country_id === c.id).length, label: 'offices', icon: Globe2 }));
  let title = 'Countries and operations';
  if (route.type === 'country') { entities = data.organization.offices.filter(o => o.country_id === route.id).map(o => ({ id: o.id, type: 'office', name: o.display_name, count: data.organization.operators.filter(p => p.assignments.some(a => a.office_id === o.id)).length, label: 'operators', icon: Building2 })); title = 'Offices in this country'; }
  if (route.type === 'office') { entities = data.organization.operators.filter(p => p.assignments.some(a => a.office_id === route.id)).map(p => ({ id: p.id, type: 'operator', name: p.display_alias, count: p.roles.length, label: 'roles', icon: UsersRound })); title = 'Office operators'; }
  return <>
    <Stats rows={rows} interviews={interviews} issues={issues}/>
    <div className="overview-columns"><Panel title={title} subtitle={route.type === 'office' ? 'Demo identities, roles and activity' : 'Explore activity from country to individual case'} className="operations-panel">
      {route.type === 'overview' && <WorldMap countries={data.organization.countries} offices={data.organization.offices} onCountrySelect={id => navigate('country',id)} onOfficeSelect={id => navigate('office',id)}/>}
      <div className="entity-list">{entities.map(entity => { const subset = allDecisions.filter(d => inScope(d, entity)); const Icon = entity.icon; return <button className="entity-row" onClick={() => navigate(entity.type, entity.id)} key={entity.id}><span className="entity-icon"><Icon size={21}/></span><span className="entity-name"><strong>{entity.name}</strong><small>{entity.count} {entity.count === 1 ? ({offices:"office",operators:"operator",roles:"role"})[entity.label] : entity.label} · {subset.length} {subset.length === 1 ? "decision" : "decisions"}</small></span><span className="entity-micro">Explore</span><ChevronRight size={18}/></button>; })}{entities.length === 0 && <Empty title="No offices added" text="This country appears on the map but has no offices or cases in the demo sample."/>}</div>
    </Panel></div><Reliance rows={rows}/>{rows.length > 0 && <section className="reasoning-showcase" aria-labelledby="reasoning-title"><div className="reasoning-heading"><div><span className="eyebrow">CASE REVIEW</span><h2 id="reasoning-title">Inside Cashy’s reasoning</h2><p>Two synthetic examples: check explanations against the evidence, even when they sound plausible.</p></div></div><div className="reasoning-cards">{rows.slice(0,2).map(row => <article className="reasoning-card" key={row.id}><span className="case-code">{row.case_id.split('-').at(-1).padStart(3,'0').replace(/^/,'CASE ')}</span><h3>{row.id.endsWith('01') ? 'A contact address is not housing' : 'Temporary shelter is not stability'}</h3><p>{row.ai.reasoning.text}</p><button type="button" onClick={() => onOpen({decision:row})}>Review case <ChevronRight size={15}/></button></article>)}</div></section>}
  </>;
}

export default function App() {
  const [route, setRoute] = useState(parseRoute); const [menuOpen, setMenuOpen] = useState(false); const [selected, setSelected] = useState(null); const [toast, setToast] = useState('');
  const audit = useLocalAudit();
  useWebMcp(audit.issues);
  const closeDetail = useCallback(() => setSelected(null), []);
  useEffect(() => { const onHash = () => { setRoute(parseRoute()); setMenuOpen(false); setSelected(null); window.scrollTo(0,0); }; window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''),4500); return () => clearTimeout(timer); },[toast]);
  useEffect(() => { if (!menuOpen) return; document.querySelector('.sidebar nav a')?.focus(); const escape = e => {if(e.key === 'Escape') setMenuOpen(false);}; window.addEventListener('keydown',escape); return () => {window.removeEventListener('keydown',escape); document.querySelector('.mobile-menu')?.focus();}; },[menuOpen]);
  const navigate = (type, id) => { window.location.hash = `/${type}${id ? `/${id}` : ''}`; };
  const rows = allDecisions.filter(d => inScope(d, route)); const interviews = data.interviews.filter(i => inScope(i, route, 'interview')); const issues = audit.issues.filter(i => rows.some(d => d.id === i.decision_id));
  const name = ({country:'countries',office:'offices',operator:'operators'})[route.type];
  const title = name ? nameOf(name, route.id) : ({overview:'Global overview', decisions:'Decisions', interviews:'Interviews', issues:'Alerts',log:'Activity log',method:'Data and methodology'})[route.type] || 'Global overview';
  const officeId = route.type === 'office' ? route.id : route.type === 'operator' ? data.organization.operators.find(p => p.id === route.id)?.assignments[0]?.office_id : null;
  const countryId = route.type === 'country' ? route.id : data.organization.offices.find(o => o.id === officeId)?.country_id;
  const validRoute = ['overview','decisions','interviews','issues','log','method'].includes(route.type) || (name && data.organization[name].some(item => item.id === route.id));
  return <div className="supervisor-app app-shell"><a className="skip-link" href="#main-content" onClick={e => {e.preventDefault();document.getElementById('main-content').focus();}}>Skip to content</a>
    {menuOpen && <button className="sidebar-scrim" aria-label="Close menu" onClick={() => setMenuOpen(false)}/>}
    <header className="institution-header"><div className="institution-main"><div className="institution-wordmark"><div><strong>UNHCR</strong><small>The UN Refugee Agency</small></div><span>Oversight</span></div><Link to="/" className="return-link">← Return to assessment</Link></div><div className="institution-band"><span><ShieldCheck size={17}/> Operator oversight · Global workspace</span><span>Cashy · Demo data</span></div></header><aside className={`sidebar ${menuOpen ? 'open' : ''}`}><a className="brand" href="#/overview"><ShieldCheck size={28}/><span>Oversight<span>CASH ASSISTANCE</span></span></a><div className="workspace"><span className="workspace-logo"><ShieldCheck size={19}/></span><div><strong>Institutional oversight</strong><small>Global workspace</small></div></div><div className="nav-label">MONITORING</div><nav>{navItems.map(([key,label,Icon]) => <a key={key} href={`#/${key}`} onClick={() => setMenuOpen(false)} aria-current={(route.type === key || (key === 'overview' && name)) ? 'page' : undefined} className={(route.type === key || (key === 'overview' && name)) ? 'active' : ''}><Icon size={19}/><span>{label}</span>{key === 'issues' && <span className="nav-count">{audit.issues.filter(i => i.status !== 'closed').length}</span>}</a>)}</nav><div className="sidebar-bottom"><a className="method-link" href="#/method"><CircleHelp size={18}/>Data and methodology</a><div className="demo-card"><span className="demo-dot"/>Demo environment<p>Synthetic data, no real people.</p></div><div className="profile"><span>SG</span><div><strong>Global supervisor</strong><small>Demo access</small></div></div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="topbar-context"><button className="mobile-menu icon-button" aria-label="Open menu" onClick={() => setMenuOpen(true)}><Menu size={22}/></button><ShieldCheck size={18}/><span>Oversight area</span><ChevronRight size={14}/><strong>Global</strong></div><div className="topbar-actions"><span className="demo-tag">LOCAL DEMO</span><button className="icon-button notification-button" aria-label="Open alerts" onClick={() => navigate('issues')}><Bell size={20}/>{audit.issues.some(i => i.status !== 'closed') && <i/>}</button><span className="avatar">SG</span></div></header>
    <main id="main-content" tabIndex="-1"><div className="breadcrumb"><button onClick={() => navigate('overview')}><Globe2 size={14}/>World</button>{countryId && route.type !== 'country' && <><ChevronRight size={14}/><button onClick={() => navigate('country',countryId)}>{nameOf('countries',countryId)}</button></>}{officeId && route.type === 'operator' && <><ChevronRight size={14}/><button onClick={() => navigate('office',officeId)}>{nameOf('offices',officeId)}</button></>}{route.type !== 'overview' && <><ChevronRight size={14}/><span>{title}</span></>}</div><div className="page-heading"><div><div className="eyebrow">HUMAN OVERSIGHT / CASH ASSISTANCE</div><h1>{validRoute ? title : 'Page not found'}</h1><p>{({decisions:'The operator’s assessment before and after Cashy’s recommendation.',interviews:'On-site interviews and language signals.',issues:'From anomalies to review: every alert has an owner.',log:'Trace the actions behind each decision.',method:'Data sources, indicator definitions and prototype limitations.'})[route.type] || 'Trace decisions. Understand changes. Keep human oversight.'}</p></div>{['overview','country','office','operator'].includes(route.type) && rows.length > 0 && <button className="button secondary" onClick={() => download(csv(rows), 'cashy-decisions-demo.csv','text/csv;charset=utf-8')}><Download size={16}/>Export data</button>}</div>
    <div className="scope-bar"><span><span className="dot teal"/>Demo sample</span><span>1 October 2026 <span className="separator">/</span> {name ? 'Selected view' : 'All operations'}</span></div>
    {audit.error && <p className="form-error" role="alert">{audit.error}</p>}
    {validRoute && route.type === 'country' && !data.organization.offices.some(o => o.country_id === route.id) ? <section className="empty-country"><span className="eyebrow">COUNTRY OVERVIEW</span><h2>No offices in the sample</h2><p>{title} has no offices, operators or cases in this demo. This geographic selection is not a census of UNHCR operations.</p>{route.id === 'country-palestine' && <p>Mandate note: assistance to Palestine refugees is primarily UNRWA’s responsibility, as UNHCR states.</p>}<button className="button secondary" onClick={() => navigate('overview')}>Back to map</button></section> : validRoute && route.type === 'office' && rows.length === 0 && interviews.length === 0 ? <section className="empty-country"><span className="eyebrow">OFFICE OVERVIEW</span><h2>No operators in the sample</h2><p>{title} has no operators or cases in this demo. UNHCR lists the office, but its actual operations are not represented here.</p><button className="button secondary" onClick={() => navigate('country',countryId)}>Back to Mexico offices</button></section> : !validRoute ? <Panel title="Page unavailable"><Empty title="This page does not exist" text="Use the navigation to return to the overview."/></Panel> : ['overview','country','office'].includes(route.type) ? <><Overview rows={rows} interviews={interviews} issues={issues} route={route} navigate={navigate} onOpen={setSelected}/><div className="section-gap"/><DecisionTable key={`${route.type}-${route.id}`} rows={rows} onOpen={setSelected} navigate={navigate} title="Decisions in scope"/></> : route.type === 'operator' ? <OperatorPage key={route.id} operatorId={route.id} rows={rows} interviews={interviews} navigate={navigate} onOpen={setSelected} stats={<Stats rows={rows} interviews={interviews} issues={issues}/>} reliance={<Reliance rows={rows}/>}/> : route.type === 'decisions' ? <><Stats rows={rows} interviews={interviews} issues={issues}/><DecisionTable rows={rows} onOpen={setSelected} navigate={navigate}/></> : route.type === 'interviews' ? <InterviewsPage interviews={interviews} onOpen={setSelected} navigate={navigate}/> : route.type === 'issues' ? <IssuesPage issues={audit.issues} updateIssue={audit.updateIssue} onOpen={setSelected} notify={setToast}/> : route.type === 'log' ? <LogPage localEvents={audit.localEvents} onOpen={setSelected}/> : <MethodPage audit={audit} notify={setToast}/>}
    <footer>UNHCR · Cashy Oversight <span>Hackathon prototype · Synthetic data · No real assessments</span><span>01.10.2026</span></footer></main></div>{selected && <DetailDialog selected={selected} onClose={closeDetail} localEvents={audit.localEvents}/>}<div role="status" aria-live="polite" className={toast ? 'toast visible' : 'toast'}>{toast}</div></div>;
}
