import { useMemo, useState } from "react"
import { Link } from "react-router-dom"
import {
  ArrowLeft,
  BarChart3,
  BrainCircuit,
  CheckCircle2,
  ChevronRight,
  CircleAlert,
  Eye,
  Filter,
  History,
  ShieldCheck,
  Users,
  XCircle,
} from "lucide-react"

const AI_CONFIDENCE_THRESHOLD = 0.78

const HISTORY = [
  { label: "09 set", fullLabel: "9 set", teams: { Alpha: 38, Bravo: 32, Charlie: 27, Delta: 24 } },
  { label: "16 set", fullLabel: "16 set", teams: { Alpha: 44, Bravo: 35, Charlie: 31, Delta: 28 } },
  { label: "23 set", fullLabel: "23 set", teams: { Alpha: 41, Bravo: 39, Charlie: 35, Delta: 30 } },
  { label: "30 set", fullLabel: "30 set", teams: { Alpha: 49, Bravo: 43, Charlie: 38, Delta: 34 } },
  { label: "07 ott", fullLabel: "7 ott", teams: { Alpha: 52, Bravo: 47, Charlie: 42, Delta: 36 } },
  { label: "14 ott", fullLabel: "14 ott", teams: { Alpha: 56, Bravo: 46, Charlie: 45, Delta: 39 } },
  { label: "21 ott", fullLabel: "21 ott", teams: { Alpha: 61, Bravo: 51, Charlie: 48, Delta: 42 } },
]

const TEAMS = [
  { id: "Alpha", name: "Team Alpha", hub: "Kakuma · Desk 1", operators: 8, decisions: 341, aiVisible: 276, aiRelied: 218, evaluated: 48, correct: 42, wrong: 6, trend: [38, 44, 41, 49, 52, 56, 61], note: "Affidamento all'AI in crescita nelle ultime due settimane." },
  { id: "Bravo", name: "Team Bravo", hub: "Kakuma · Desk 3", operators: 7, decisions: 293, aiVisible: 241, aiRelied: 164, evaluated: 45, correct: 43, wrong: 2, trend: [32, 35, 39, 43, 47, 46, 51], note: "Buon equilibrio tra supporto AI e verifica autonoma." },
  { id: "Charlie", name: "Team Charlie", hub: "Dadaab · Hagadera", operators: 6, decisions: 266, aiVisible: 207, aiRelied: 149, evaluated: 39, correct: 31, wrong: 8, trend: [27, 31, 35, 38, 42, 45, 48], note: "I casi già valutati mostrano un'area di apprendimento prioritaria." },
  { id: "Delta", name: "Team Delta", hub: "Dadaab · Ifo", operators: 5, decisions: 233, aiVisible: 174, aiRelied: 99, evaluated: 36, correct: 34, wrong: 2, trend: [24, 28, 30, 34, 36, 39, 42], note: "Bassa dipendenza dall'AI, con esito positivo sui controlli." },
]

const TEAM_COLORS = { Alpha: "#0072BC", Bravo: "#18375F", Charlie: "#1B8A5A", Delta: "#E6A700" }
const percent = (value, total) => (total ? Math.round((value / total) * 100) : 0)

function MetricCard({ icon: Icon, label, value, detail, tone = "blue" }) {
  const tones = { blue: "bg-[#EFF7FE] text-[#18375F]", green: "bg-[#E8F5EC] text-[#1D5E36]", yellow: "bg-[#FFF799] text-[#4A3B00]", red: "bg-[#FDECEA] text-[#8A1C12]" }
  return (
    <article className="rounded border border-[#D9E5EF] bg-white p-5 shadow-[0_1px_2px_rgba(24,55,95,0.06)]">
      <div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-[#4D4D4D]">{label}</p><p className="mt-2 text-4xl font-black tracking-tight text-[#18375F]">{value}</p></div><span className={`flex h-10 w-10 items-center justify-center rounded ${tones[tone]}`}><Icon className="h-5 w-5" aria-hidden="true" /></span></div>
      <p className="mt-3 text-sm leading-relaxed text-[#4D4D4D]">{detail}</p>
    </article>
  )
}

function TeamBadge({ team }) {
  return <span className="inline-flex items-center gap-2 font-bold text-[#1A1A1A]"><span className="h-3 w-3 rounded-sm" style={{ backgroundColor: TEAM_COLORS[team.id] }} aria-hidden="true" />{team.name}</span>
}

function HistoryChart({ selectedTeam, onSelectTeam }) {
  const max = Math.max(...HISTORY.flatMap((week) => Object.values(week.teams)))
  return <div><div className="flex h-64 items-end gap-3 border-b-2 border-[#1A1A1A] px-2 pb-0 sm:gap-5">{HISTORY.map((week) => <div key={week.label} className="flex min-w-0 flex-1 items-end justify-center gap-1.5 self-stretch">{TEAMS.map((team) => { const height = `${(week.teams[team.id] / max) * 100}%`; const active = selectedTeam === "all" || selectedTeam === team.id; return <button key={team.id} type="button" title={`${week.fullLabel}: ${team.name}, ${week.teams[team.id]} decisioni`} onClick={() => onSelectTeam(team.id)} className={`group relative flex h-full flex-1 items-end focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#18375F] ${active ? "" : "opacity-20"}`}><span className="w-full rounded-t-sm transition-[height,opacity] duration-300 group-hover:opacity-75" style={{ height, backgroundColor: TEAM_COLORS[team.id] }} /></button> })}</div>)}</div><div className="mt-3 flex gap-3 px-2 sm:gap-5">{HISTORY.map((week) => <span key={week.label} className="flex-1 text-center text-xs font-semibold text-[#4D4D4D]">{week.label}</span>)}</div></div>
}

export default function QualityDashboard() {
  const [selectedTeam, setSelectedTeam] = useState("all")
  const [showEvaluatedOnly, setShowEvaluatedOnly] = useState(false)
  const activeTeam = TEAMS.find((team) => team.id === selectedTeam)
  const totals = useMemo(() => TEAMS.reduce((result, team) => ({ decisions: result.decisions + team.decisions, aiRelied: result.aiRelied + team.aiRelied, aiVisible: result.aiVisible + team.aiVisible, evaluated: result.evaluated + team.evaluated, correct: result.correct + team.correct, wrong: result.wrong + team.wrong }), { decisions: 0, aiRelied: 0, aiVisible: 0, evaluated: 0, correct: 0, wrong: 0 }), [])
  const displayedTeams = showEvaluatedOnly ? TEAMS.filter((team) => team.evaluated > 0) : TEAMS

  return <div className="min-h-screen bg-[#F4F7FB] text-[#1A1A1A]">
    <header><div className="border-b-2 border-[#005A96] bg-[#0072BC] text-white"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-8"><Link to="/" className="inline-flex items-center gap-2 text-sm font-bold text-white hover:underline"><ArrowLeft className="h-4 w-4" aria-hidden="true" />Torna alla valutazione</Link><div className="flex items-center gap-3"><div className="leading-none"><div className="text-[26px] font-black tracking-tight">UNHCR</div><div className="mt-1 text-[10px] font-semibold">The UN Refugee Agency</div></div><span className="h-8 w-px bg-white/60" aria-hidden="true" /><span className="text-lg font-semibold">Qualità delle decisioni</span></div></div></div><div className="bg-[#18375F] text-white"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-4 px-4 py-3 sm:px-8"><div className="flex items-center gap-2 text-sm"><ShieldCheck className="h-4 w-4 text-[#FFD100]" aria-hidden="true" />Monitoraggio operatori · Operazione Kenya</div><span className="hidden text-xs text-white/75 sm:inline">Dati aggiornati al 21 ottobre 2026</span></div></div></header>
    <main className="mx-auto max-w-[1440px] px-4 py-8 sm:px-8"><nav aria-label="Percorso" className="flex items-center gap-2 text-sm text-[#4D4D4D]"><Link to="/" className="text-[#0072BC] hover:underline">Aiuti in denaro</Link><span aria-hidden="true">/</span><span>Qualità delle decisioni</span></nav><div className="mt-4 flex flex-col justify-between gap-5 border-b-2 border-[#1A1A1A] pb-5 lg:flex-row lg:items-end"><div><h1 className="text-3xl font-bold sm:text-4xl">Qualità del lavoro dei team</h1><p className="mt-3 max-w-3xl text-lg leading-relaxed text-[#4D4D4D]">Segui il volume delle decisioni, l&apos;uso del suggerimento AI e l&apos;accuratezza sui casi già valutati. L&apos;obiettivo è sostenere il giudizio degli operatori, non sostituirlo.</p></div><div className="flex items-center gap-2 rounded border border-[#7DB2DC] bg-[#EFF7FE] px-3 py-2 text-sm font-bold text-[#18375F]"><BrainCircuit className="h-4 w-4" aria-hidden="true" />Suggerimento visibile sopra {Math.round(AI_CONFIDENCE_THRESHOLD * 100)}% di confidenza</div></div>
      <section aria-labelledby="overview-title" className="mt-8"><h2 id="overview-title" className="sr-only">Riepilogo qualità</h2><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={BarChart3} label="Decisioni registrate" value={totals.decisions} detail="Nel periodo monitorato da tutti i team" /><MetricCard icon={BrainCircuit} label="Decisioni che seguono AI" value={`${percent(totals.aiRelied, totals.aiVisible)}%`} detail={`${totals.aiRelied} su ${totals.aiVisible} con suggerimento visibile`} tone="yellow" /><MetricCard icon={CheckCircle2} label="Controlli corretti" value={totals.correct} detail={`Su ${totals.evaluated} casi già valutati`} tone="green" /><MetricCard icon={CircleAlert} label="Controlli da rivedere" value={totals.wrong} detail={`${percent(totals.wrong, totals.evaluated)}% dei casi già valutati`} tone="red" /></div></section>
      <div className="mt-8 grid grid-cols-1 gap-8 xl:grid-cols-[minmax(0,1.45fr)_minmax(340px,0.8fr)]"><section aria-labelledby="history-title" className="rounded border border-[#D9E5EF] bg-white p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 border-b border-[#D9E5EF] pb-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><History className="h-5 w-5 text-[#18375F]" aria-hidden="true" /><h2 id="history-title" className="text-xl font-bold">Decisioni nel tempo</h2></div><p className="mt-1 text-sm text-[#4D4D4D]">Conteggio settimanale per team, ultimi 7 aggiornamenti.</p></div><span className="text-sm font-semibold text-[#4D4D4D]">Clicca una serie per filtrare</span></div><div className="mt-7"><HistoryChart selectedTeam={selectedTeam} onSelectTeam={setSelectedTeam} /></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-3 border-t border-[#D9E5EF] pt-4">{TEAMS.map((team) => <button key={team.id} type="button" onClick={() => setSelectedTeam(selectedTeam === team.id ? "all" : team.id)} className={`text-sm ${selectedTeam === team.id ? "font-black text-[#18375F]" : "font-semibold text-[#4D4D4D]"}`}><TeamBadge team={team} /></button>)}</div></section><section aria-labelledby="signal-title" className="rounded border-2 border-[#7DB2DC] bg-[#EFF7FE] p-5 sm:p-7"><div className="flex items-center gap-2"><Eye className="h-5 w-5 text-[#18375F]" aria-hidden="true" /><h2 id="signal-title" className="text-xl font-bold">Segnale da monitorare</h2></div><p className="mt-4 text-5xl font-black text-[#18375F]">{percent(totals.aiRelied, totals.aiVisible)}%</p><p className="mt-1 font-bold">delle decisioni ha seguito il suggerimento AI</p><div className="mt-5 h-3 overflow-hidden rounded-sm bg-white"><div className="h-full bg-[#FFD100]" style={{ width: `${percent(totals.aiRelied, totals.aiVisible)}%` }} /></div><p className="mt-4 text-sm leading-relaxed text-[#4D4D4D]">Il dato è un segnale operativo, non un giudizio individuale. Va letto insieme agli esiti dei casi di controllo e alla difficoltà dei fascicoli.</p><div className="mt-6 border-t border-[#B9D6EE] pt-4 text-sm"><span className="font-bold text-[#18375F]">Soglia attiva:</span> l&apos;AI resta nascosta quando la confidenza è inferiore al {Math.round(AI_CONFIDENCE_THRESHOLD * 100)}%.</div></section></div>
      <section aria-labelledby="teams-title" className="mt-8 rounded border border-[#D9E5EF] bg-white"><div className="flex flex-col justify-between gap-4 border-b border-[#D9E5EF] p-5 sm:flex-row sm:items-center sm:p-7"><div><div className="flex items-center gap-2"><Users className="h-5 w-5 text-[#18375F]" aria-hidden="true" /><h2 id="teams-title" className="text-xl font-bold">Confronto tra team</h2></div><p className="mt-1 text-sm text-[#4D4D4D]">La combinazione tra dipendenza dall&apos;AI e controlli sbagliati aiuta a scegliere dove fare coaching.</p></div><button type="button" onClick={() => setShowEvaluatedOnly((value) => !value)} className={`inline-flex items-center justify-center gap-2 rounded border-2 px-4 py-2 text-sm font-bold ${showEvaluatedOnly ? "border-[#0072BC] bg-[#EFF7FE] text-[#0072BC]" : "border-[#1A1A1A] bg-white text-[#1A1A1A]"}`}><Filter className="h-4 w-4" aria-hidden="true" />{showEvaluatedOnly ? "Mostra tutti i team" : "Solo team con controlli"}</button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#F4F7FB] text-xs uppercase tracking-wide text-[#4D4D4D]"><tr><th className="px-5 py-3 font-bold sm:px-7">Team</th><th className="px-3 py-3 font-bold">Decisioni</th><th className="px-3 py-3 font-bold">Segue AI</th><th className="px-3 py-3 font-bold">Controlli</th><th className="px-3 py-3 font-bold">Corretti</th><th className="px-3 py-3 font-bold">Sbagliati</th><th className="px-5 py-3 text-right font-bold sm:px-7">Dettaglio</th></tr></thead><tbody className="divide-y divide-[#D9E5EF]">{displayedTeams.map((team) => <tr key={team.id} className={`transition-colors hover:bg-[#EFF7FE] ${selectedTeam === team.id ? "bg-[#EFF7FE]" : ""}`}><td className="px-5 py-4 sm:px-7"><TeamBadge team={team} /><span className="mt-1 block text-xs text-[#4D4D4D]">{team.hub} · {team.operators} operatori</span></td><td className="px-3 py-4 font-bold">{team.decisions}</td><td className="px-3 py-4"><span className="font-bold text-[#6B4E00]">{percent(team.aiRelied, team.aiVisible)}%</span><span className="mt-1 block text-xs text-[#4D4D4D]">{team.aiRelied}/{team.aiVisible}</span></td><td className="px-3 py-4 font-bold">{team.evaluated}</td><td className="px-3 py-4 font-bold text-[#1D5E36]">{team.correct} <span className="font-normal text-[#4D4D4D]">({percent(team.correct, team.evaluated)}%)</span></td><td className="px-3 py-4 font-bold text-[#8A1C12]">{team.wrong}</td><td className="px-5 py-4 text-right sm:px-7"><button type="button" onClick={() => setSelectedTeam(team.id)} className="inline-flex items-center gap-1 font-bold text-[#0072BC] hover:underline">Apri <ChevronRight className="h-4 w-4" aria-hidden="true" /></button></td></tr>)}</tbody></table></div></section>
      {activeTeam && <section aria-labelledby="team-detail-title" className="mt-8 rounded border-2 border-[#18375F] bg-white p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 border-b border-[#D9E5EF] pb-5 sm:flex-row sm:items-start"><div><p className="text-sm font-bold uppercase tracking-wide text-[#0072BC]">Scheda di monitoraggio</p><h2 id="team-detail-title" className="mt-1 text-2xl font-bold"><TeamBadge team={activeTeam} /></h2><p className="mt-2 text-sm text-[#4D4D4D]">{activeTeam.note}</p></div><button type="button" onClick={() => setSelectedTeam("all")} className="text-sm font-bold text-[#0072BC] hover:underline">Chiudi dettaglio</button></div><div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2"><div><h3 className="font-bold">Andamento decisioni</h3><div className="mt-4 flex h-32 items-end gap-3 border-b-2 border-[#1A1A1A]">{activeTeam.trend.map((value, index) => <div key={`${activeTeam.id}-${index}`} className="flex flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-bold">{value}</span><div className="w-full rounded-t-sm bg-[#0072BC]" style={{ height: `${(value / Math.max(...activeTeam.trend)) * 90}%` }} /><span className="text-[10px] text-[#4D4D4D]">S{index + 1}</span></div>)}</div></div><div><h3 className="font-bold">Esito dei casi già valutati</h3><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded bg-[#E8F5EC] p-4"><CheckCircle2 className="h-5 w-5 text-[#1D5E36]" aria-hidden="true" /><p className="mt-2 text-2xl font-black text-[#1D5E36]">{activeTeam.correct}</p><p className="text-sm font-semibold text-[#1D5E36]">decisioni corrette</p></div><div className="rounded bg-[#FDECEA] p-4"><XCircle className="h-5 w-5 text-[#8A1C12]" aria-hidden="true" /><p className="mt-2 text-2xl font-black text-[#8A1C12]">{activeTeam.wrong}</p><p className="text-sm font-semibold text-[#8A1C12]">da rivedere</p></div></div><p className="mt-4 text-sm leading-relaxed text-[#4D4D4D]">Su {activeTeam.evaluated} fascicoli di controllo, il team ha raggiunto il {percent(activeTeam.correct, activeTeam.evaluated)}% di accuratezza.</p></div></div></section>}
    </main>
  </div>
}